RABBITMQ_HOST = "localhost"
RABBITMQ_PORT = 5672
RABBITMQ_USER = "guest"
RABBITMQ_PASSWORD = "guest"

MAX_RETRIES = 3
PROCESSING_SECONDS = 0.1
TIMEOUT_SECONDS = 5
RETRY_BACKOFF_SECONDS = 0.5

DEAD_LETTER_QUEUE = "dead_letter_queue"
LOG_LEVEL = "INFO"